# HERE ARE SOME OF SIMPLE PROTOTYPES OF PROGRAMS, WHICH I HAVE CREATED INORDER TO PRACTICE CERTAIN ASPECTS OF PYTHON. 
# THESE ARE NOT FULL-FLEDGED PROGRAMS, 
# BUT RATHER MY PRACTICE OF CERTAIN CONCEPTS AND GETTING USED TO THE LANGUAGE.
# SO IF THERE ARE BUGS OR LOGICAL FLAWS PLEASE CONSIDER CREATING A ISSUE IN THE REPOSITORY, I WILL TRY TO FIX IT AS SOON AS POSSIBLE.


# 1. MOVIE RATING SYSTEM


